services:
  nginx:
    image: nginx:latest
    container_name: ${NGINX_CONTAINER_NAME}
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}" # Перенаправление на localhost
    volumes:
      - ./:/var/www/html
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
    environment:
      - NGINX_PORT=${NGINX_PORT}
    depends_on:
      - php
    networks:
      - app_network

  php:
    build:
      context: ./config/php
      dockerfile: Dockerfile
    container_name: ${PHP_CONTAINER_NAME}
    volumes:
      - ./:/var/www/html
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - app_network
    working_dir: /var/www/html
  
networks:
  app_network:
    driver: bridge